---
- name: "{{ myansible_prefix_task_name }}Install personnal repos"
  include_tasks: personnal.yml
  when: repo_origin == 'false'

- name: "{{ myansible_prefix_task_name }}Install originals repos"
  include_tasks: original.yml
  when: repo_origin == 'true'
