---
- name: "{{ myansible_prefix_task_name }}Remove debian repo"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ remove_repos }}"
  when: remove_other_repo == 'true' and remove_repos | length > 0

- name: "{{ myansible_prefix_task_name }}Install originals repo"
  template:
    src: debian.list.j2
    dest: /etc/apt/sources.list.d/debian.list
    owner: root
    group: root
